import keyMirror from 'keymirror';

module.exports = keyMirror({
  REQUEST_CONNECTION: null,
  RECEIVE_WELCOME: null,

  COMMAND_JOIN: null,
  COMMAND_ME: null,
  COMMAND_MSG: null,
  COMMAND_NICK: null,
  COMMAND_NOTICE: null,
  COMMAND_PART: null,
  COMMAND_PART_ALL: null,
  COMMAND_PING: null,
  COMMAND_QUERY: null,
  COMMAND_QUIT: null,
  COMMAND_IGNORE: null,
  COMMAND_WHOIS: null,
  COMMAND_CHAT: null,
  COMMAND_HELP: null,
  COMMAND_UNRECOGNIZED: null,

  SELECT_CHANNEL: null,
  RECEIVE_NAMES: null,
  RECEIVE_MESSAGE: null,
  RECEIVE_DIRECT_MESSAGE: null,
  SEND_MESSAGE: null,
  RECEIVE_NOTICE: null,
  RECEIVE_JOIN: null,
  RECEIVE_AWAY: null,
  RECEIVE_PART: null,
  RECEIVE_QUIT: null,
  RECEIVE_TOPIC: null,
  RECEIVE_NICK: null,
});
